name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Publication branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check out.
        uses: actions/checkout@v3
    
      - name: Activate Python.
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
    
      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -r pelreqs.txt

      - name: Build the public site.
        run: pelican content -o output -s pelicanconf.py

      - name: Debug build.
        run: |
          git status
          git stash --include-untracked
          git remote -v
          git branch -r

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.CHRONICLES_DEPLOY }}
          publish_branch: gh-pages
          publish_dir: ./output
